'use strict';
const fs=require('node:fs');const {calcularSolicitud}=require('../dist-motor/entrada');
const cases=require('./fixtures/casos-fuente.json');
const m={id:'MCI-ALTAMIRANO',fuente:'Metrología Causal I',seccion:'Caso de cierre C·4–C·8',clase:'ejemplo formal histórico, procedimiento incompatible con orden actual',nodos:['ECP','PSM','FRO','BM'],aristas:[['FRO','ECP',.45,.75],['FRO','PSM',.4,.7],['ECP','BM',.5,.85],['ECP','FRO',.2,.45],['PSM','FRO',.25,.5],['FRO','BM',.3,.6],['BM','D',.65,.85]].map(([origen,destino,min,max])=>({origen,destino,min,max})),resultadoFuente:{ECP:.308,PSM:.118,FRO:.381,BM:.193}};
if(!cases.some(x=>x.id===m.id)){cases.push(m);fs.writeFileSync('auditoria/fixtures/casos-fuente.json',JSON.stringify(cases,null,2));}
const out=[];
function run(f){const edges=f.aristas.map((e,i)=>({...e,id:String(i),rango:{min:e.min,max:e.max},evidenciaNivel:1}));const r=calcularSolicitud({analisis:{titulo:'Fuente transcrita',pregunta:f.id,fenomeno:{descripcion:'Comparación'},eventoDeterminado:{id:'D'},nodosActivos:f.nodos.map(id=>({id})),relacionesInternas:edges.filter(e=>e.destino!=='D'),conexionesCierre:edges.filter(e=>e.destino==='D')},medicionesSolicitadas:['rStar','robustez']});out.push({id:f.id,fuente:f.fuente,seccion:f.seccion,clase:f.clase,resultadoFuente:f.resultadoFuente,resultadoMotor:r.rStar,estado:r.resultados.rStar.estado,declaracion:r.declaracion,escenarios:Object.fromEntries(Object.entries(r.escenarios).map(([k,v])=>[k,{vector:v.vector,residuo:v.residuo,diagnostico:v.diagnostico,motivo:v.motivo}]))});}
cases.forEach(run);
for(const f of require('./fixtures/matrices-corpus.json')){const n=f.matrizLiteral.length-1;run({id:f.id,fuente:f.fuente,seccion:`línea ${f.linea}, ${f.variable}`,clase:f.clase,nodos:Array.from({length:n},(_,i)=>'N'+(i+1)),aristas:f.matrizLiteral.slice(0,n).flatMap((row,i)=>row.map((v,j)=>({origen:'N'+(i+1),destino:j===n?'D':'N'+(j+1),min:v,max:v}))).filter(e=>e.min!==0),resultadoFuente:'Ver tabla/código de la sección; no se inventa oracle PF actual'});}
fs.writeFileSync('auditoria/evidencia/comparacion-corpus.json',JSON.stringify(out,null,2));console.log(out.map(x=>({id:x.id,estado:x.estado,vector:x.resultadoMotor.map(n=>n.valor),declaracion:x.declaracion?.nivel})));
