'use strict';
// Servidor local construido sin modificar runtime: npm start -- --port 3110
const fs=require('node:fs'),assert=require('node:assert/strict');
const {calcularSolicitud}=require('../dist-motor/entrada');
const {generarHTML}=require('../dist-motor/expediente');
const {construirSolicitud}=require('../components/constructor/entrada');
const f={familia:'contabilidad_ontologica',dominio:'Auditoría sintética',titulo:'AUD-W02-PRODUCCION',pregunta:'¿Se conserva el cálculo entre capas?',descripcion:'Fixture sintético PF, sin hechos reales',evento:'D sintético',nodos:[{id:'a',nombre:'A',componentesS:['0','.4','.1'],estrategiaAlpha:'discriminado',alphaValor:'.08',declarado:'x\ny',observado:'x',coincidencias:'1',beneficio:'30'},{id:'b',nombre:'B',componentesS:['.5','.5','.7'],estrategiaAlpha:'discriminado',alphaValor:'.03',declarado:'x\ny',observado:'x',coincidencias:'1',beneficio:'10'}],relaciones:[['a','a','.9'],['a','b','.4'],['b','a','.1'],['b','b','.6'],['a','D','1']].map(([origen,destino,v],i)=>({id:String(i),origen,destino,evidenciaNivel:'1',min:v,max:v})),mediciones:['rStar','s','rStarNeta','alpha','delta','iic','bStar','dTotal','ajusteDebitor','robustez'],unidadDanio:'MXN',unidadBeneficio:'MXN',tInvertido:'100',tImpedido:'20',tTrayectoria:'30'};
const q=construirSolicitud(f);fs.writeFileSync('auditoria/fixtures/diferencial.json',JSON.stringify(q,null,2));
async function post(endpoint,body){const r=await fetch('http://localhost:3110/api/'+endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,200);return endpoint==='calcular'?r.json():r.text();}
(async()=>{const server=require('node:child_process').spawn(process.execPath,['node_modules/next/dist/bin/next','start','--port','3110'],{stdio:['ignore','pipe','pipe']}); try { await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Servidor no listo')),30000);server.stdout.on('data',x=>{if(String(x).includes('Ready')){clearTimeout(timer);resolve();}});server.on('error',reject);server.on('exit',code=>reject(Error('Servidor terminó '+code)));});const r=await post('calcular',q),local=JSON.parse(JSON.stringify(calcularSolicitud(q)));assert.deepEqual(r,local);const json=JSON.parse(JSON.stringify(r));assert.deepEqual(json,r);const h=await post('expediente',{resultado:r,metadatos:{titulo:f.titulo}});assert.equal(h,generarHTML(r,r.modelo,{titulo:f.titulo}));const hAlterado=await post('expediente',{resultado:r,analisis:{nodosActivos:[]},insumos:{danio:{tInvertido:{monto:999}}},metadatos:{titulo:f.titulo}});assert.equal(hAlterado,h);assert.deepEqual(json,r);
 const audit={servidor:'Next producción local, port3110',mismoMotorRespuestaHTTP:true,mismoHTMLFuncionYHTTP:true,exportJSONSinCambio:true,snapshotNoRecalculaAunqueSolicitudCambie:true,uiProduccionObservado:{rStar:['80.00%','20.00%'],s:['16.67%','56.67%'],neta:['66.67%','8.67%'],alpha:['8.00%','3.00%'],delta:['0.720000','0.170000'],bStar:[.75,.25],adCentral:[119.99999999476131,30.00000000523869]},respuestas:r,conservacion:{unidadBEnRespuesta:r.resultados.bStar.unidad,totalBEnRespuesta:r.resultados.bStar.total,unidadBHTML:h.replace(/data:image[^" ]+/g,'').includes('MXN'),insumosOriginalesExportados:Object.hasOwn(r,'insumos'),configuracionOriginalExportada:Object.hasOwn(r,'configuracion')},limite:'UI verificada en producción por navegador; descarga cloud no entregó evento. Comparación exacta HTTP/HTML/JSON ejecutada localmente, no se afirma captura byte a byte de respuesta de red de producción.'};fs.writeFileSync('auditoria/evidencia/diferencial.json',JSON.stringify(audit,null,2));console.log('Diferencial HTTP/HTML/JSON exacto: PASS. UI producción coincide con formato; pérdidas de trazabilidad caracterizadas.');}finally{server.kill('SIGTERM');}})().catch(e=>{console.error(e);process.exitCode=1});
