var fs = require('fs');
var c = fs.readFileSync('dist-motor/expediente.js', 'utf8');

var ini = c.indexOf('\nfunction seccion5(');
var fin = c.indexOf('\nfunction seccion6(');

if (ini === -1 || fin === -1) {
  console.error('ERROR: no se encontraron los marcadores.');
  process.exit(1);
}

var fn = [
'function seccion5(resultado, grafoCausal, metadatos) {',
'  var decl  = resultado.declaracion;',
'  var lider = resultado.rStar.filter(function(r){',
'    var nd = grafoCausal.nodos.find(function(n){ return n.nombre === r.nodo; });',
'    return nd && nd.tipo !== \'final\';',
'  }).sort(function(a,b){ return b.valor - a.valor; })[0];',
'',
'  var inversion = resultado.delta.some(function(d){ return d.resultado && d.resultado.signo === \'sobreasuncion\'; }) &&',
'                  resultado.delta.some(function(d){ return d.resultado && d.resultado.signo === \'brecha\'; });',
'',
'  var invTxt = inversion',
'    ? \'<p><strong>Inversi\\u00f3n causal detectada:</strong> El sistema muestra el patr\\u00f3n del Teorema de Inversi\\u00f3n Causal: hay nodos con brecha activa y nodos con sobreasunci\\u00f3n simult\\u00e1neamente.</p>\'',
'    : \'\';',
'',
'  var iicNodos = resultado.serieII.filter(function(n){ return n.iic !== null; });',
'  var iicTxt = iicNodos.length',
'    ? \'<p><strong>Integridad del dise\\u00f1o (Serie II):</strong> \' + iicNodos.map(function(n){ return n.interpretacionIIC + \' \' + n.interpretacionFA; }).join(\' \') + \'</p>\'',
'    : \'\';',
'',
'  var narrativa = resultado.rStar.filter(function(r){',
'    var nd = grafoCausal.nodos.find(function(n){ return n.nombre === r.nodo; });',
'    return nd && nd.tipo !== \'final\';',
'  }).sort(function(a,b){ return b.valor - a.valor; }).map(function(r) {',
'    var nd = grafoCausal.nodos.find(function(n){ return n.nombre === r.nodo; });',
'    var a  = resultado.alpha.find(function(x){ return x.nodo === r.nodo; });',
'    var d  = resultado.delta.find(function(x){ return x.nodo === r.nodo; });',
'    return \'El nodo <strong>\' + r.nodo + \'</strong> (\' + (nd?tipoLabel(nd.tipo):\'\')+\') \' +',
'      \'exhibe R* = \' + (r.valor*100).toFixed(2) + \'%, R*_neta = \' + (r.neta*100).toFixed(2) + \'%, \' +',
'      \'\\u03b1 = \' + (a?(a.valor*100).toFixed(1)+\'%\':\'\\u2014\') + \'. \' +',
'      (d && d.resultado ? \'\\u0394 = \' + d.resultado.valor.toFixed(3) + \' (\' + d.resultado.signo + \').\' : \'\');',
'  }).join(\' \');',
'',
'  var tipos = {};',
'  grafoCausal.nodos.forEach(function(nd){',
'    if (nd.tipo !== \'final\') { if (!tipos[nd.tipo]) tipos[nd.tipo] = []; tipos[nd.tipo].push(nd.nombre); }',
'  });',
'  var equiv = {',
'    diseno:\'Derecho: autor mediato (quien dise\\u00f1\\u00f3 el sistema que hizo posible el da\\u00f1o) \\u00b7 Auditor\\u00eda: responsable institucional de dise\\u00f1o \\u00b7 Medicina: factor etiol\\u00f3gico estructural\',',
'    ejecucion:\'Derecho: ejecutor (quien llev\\u00f3 a cabo el acto) \\u00b7 Auditor\\u00eda: operador del protocolo \\u00b7 Medicina: agente causal directo\',',
'    institucional:\'Derecho: persona moral \\u00b7 Auditor\\u00eda: entidad auditada \\u00b7 Econom\\u00eda: agente estructural\',',
'    normativo:\'Derecho: norma habilitante \\u00b7 Pol\\u00edtica p\\u00fablica: marco regulatorio\'',
'  };',
'  var filasE = Object.keys(tipos).map(function(t){',
'    return \'<tr><td>\' + t + \'</td><td>\' + tipos[t].join(\', \') + \'</td><td>\' + (equiv[t]||\'\\u2014\') + \'</td></tr>\';',
'  }).join(\'\');',
'',
'  // Detectar patron: nodo lider de ejecucion con S alto',
'  var liderNd = grafoCausal.nodos.find(function(n){ return n.nombre === lider.nodo; });',
'  var liderS = (lider.valor > 0) ? (1 - (lider.neta / lider.valor)) : 0;',
'  var advertenciaTxt = \'\';',
'  if (liderNd && liderNd.tipo === \'ejecucion\' && liderS >= 0.50) {',
'    var pctEstructural = (liderS * 100).toFixed(1);',
'    var pctNeta = (lider.neta * 100).toFixed(1);',
'    var nodosDiseno = grafoCausal.nodos.filter(function(n){ return n.tipo === \'diseno\'; }).map(function(n){ return n.nombre; });',
'    var disenoTxt = nodosDiseno.length > 0 ? \' Los nodos de dise\\u00f1o que construyeron esas condiciones son: \' + nodosDiseno.join(\', \') + \'.\' : \'\';',
'    advertenciaTxt = \'<div class="declaracion-box" style="border-color:#e67e22;margin-bottom:16px">\' +',
'      \'<span class="declaracion-nivel" style="color:#e67e22">Advertencia de lectura</span>\' +',
'      \'<span class="declaracion-texto">R* = \' + (lider.valor*100).toFixed(2) + \'% en un nodo de ejecuci\\u00f3n con sustituibilidad S = \' + (liderS*100).toFixed(1) + \'% no indica responsabilidad de dise\\u00f1o. \' +',
'      \'Indica que este nodo es el punto de convergencia de cadenas causales dise\\u00f1adas por otros. \' +',
'      \'El \' + pctEstructural + \'% de su peso causal es estructural: cualquier actor en esa posici\\u00f3n, bajo las mismas condiciones, habr\\u00eda producido el mismo resultado. \' +',
'      \'El peso causal atribuible espec\\u00edficamente a este actor es R*_neta = \' + pctNeta + \'%.\' +',
'      disenoTxt + \'</span></div>\';',
'  }',
'',
'  return \'<div class="seccion salto-pagina">\' +',
'    \'<h2>Secci\\u00f3n 5 \\u00b7 Declaraci\\u00f3n Narrativa</h2>\' +',
'    \'<div class="nota">Tono: neutro / forense. El an\\u00e1lisis describe la estructura causal \\u2014 no determina culpabilidad.</div>\' +',
'    advertenciaTxt +',
'    \'<h3>5.1 S\\u00edntesis del an\\u00e1lisis causal</h3>\' +',
'    \'<p>El an\\u00e1lisis aplic\\u00f3 el M\\u00e9todo Prometeo en sus tres series sobre un grafo causal de \' +',
'    grafoCausal.nodos.filter(function(n){ return n.tipo !== \'final\'; }).length + \' nodos y \' +',
'    grafoCausal.aristas.length + \' aristas. El nodo de mayor peso causal es <strong>\' +',
'    lider.nodo + \'</strong> con R* = \' + (lider.valor*100).toFixed(2) + \'%.</p>\' +',
'    invTxt +',
'    \'<h3>5.2 Distribuci\\u00f3n de responsabilidad causal</h3><p>\' + narrativa + \'</p>\' +',
'    iicTxt +',
'    \'<h3>5.3 Robustez del an\\u00e1lisis (Serie III)</h3>\' +',
'    \'<p>El ranking \\u03c3(R*) se mantuvo estable en el <strong>\' + resultado.estabilidad.pctEstabilidad.toFixed(1) +',
'    \'%</strong> del espacio de par\\u00e1metros plausibles. Declaraci\\u00f3n nivel <strong>\' + decl.nivel + \'</strong>. \' +',
'    decl.descripcion + \'</p>\' +',
'    \'<h3>5.4 Tabla de equivalencias disciplinares (Metrolog\\u00eda Causal Vol. II)</h3>\' +',
'    \'<div class="nota">La ontolog\\u00eda no cambia \\u2014 el lenguaje s\\u00ed.</div>\' +',
'    \'<table><thead><tr><th>Tipo de nodo</th><th>Nodos</th><th>Equivalencias por dominio</th></tr></thead><tbody>\' + filasE + \'</tbody></table>\' +',
'    \'</div>\\n\';',
'}'
].join('\n');

var nuevo = c.substring(0, ini) + '\n' + fn + '\n' + c.substring(fin);
fs.writeFileSync('dist-motor/expediente.js', nuevo);
console.log('Listo.');
