'use strict';
// Estas pruebas fijan los defectos observados. No equivalen a aceptación doctrinal.
const {test}=require('node:test'),a=require('node:assert/strict');
const {calcularSolicitud}=require('../dist-motor/entrada');
const {calcularRStar}=require('../dist-motor/r_estrella');
const {calcularBStar}=require('../dist-motor/b_estrella');
const {generarHTML}=require('../dist-motor/expediente');
const {construirSolicitud}=require('../components/constructor/entrada');
function modelo(){return {titulo:'Auditoría',pregunta:'P',fenomeno:{descripcion:'F'},eventoDeterminado:{id:'D'},nodosActivos:[{id:'a'},{id:'b'}],relacionesInternas:[['a','a',.9],['a','b',.4],['b','a',.1],['b','b',.6]].map(([origen,destino,v],i)=>({id:String(i),origen,destino,rango:{min:v,max:v}})),conexionesCierre:[{id:'cierre',origen:'a',destino:'D',evidenciaNivel:1,rango:{min:1,max:1}}]};}
test('AU-01 regresión: cierre E0 no acredita clausura y D queda externo',()=>{const m=modelo();m.conexionesCierre[0].evidenciaNivel=0;a.equal(calcularSolicitud({analisis:m,medicionesSolicitadas:['rStar']}).resultados.rStar.estado,'indeterminado');m.conexionesCierre=[{id:'cierre',origen:'a',destino:'D',evidenciaNivel:1,rango:{min:1,max:1}}];const r=calcularSolicitud({analisis:m,medicionesSolicitadas:['rStar']});a.equal(r.resultados.rStar.estado,'calculado');a.ok(Math.abs(r.rStar[0].valor-.8)<1e-9);a.ok(!r.escenarios.central.W_E.ids.includes('D'));});
test('AUD-02 regresión: unidad y total B* se conservan en HTML',()=>{const r=calcularSolicitud({analisis:modelo(),medicionesSolicitadas:['bStar'],insumos:{beneficios:{unidad:'MXN',valores:[{id:'a',valor:30},{id:'b',valor:10}]}}});a.equal(r.resultados.bStar.unidad,'MXN');a.equal(r.resultados.bStar.total,40);const h=generarHTML(r);a.equal(h.replace(/data:image[^" ]+/g,'').includes('MXN'),true);a.equal(h.includes('&quot;total&quot;: 40'),true);});
test('AUD-03 regresión: α externo llega al linter',()=>{const r=calcularSolicitud({analisis:modelo(),medicionesSolicitadas:['delta'],insumos:{insumosAlpha:[{id:'a',estrategia:'discriminado',valor:.1},{id:'b',estrategia:'discriminado',valor:.2}]}});a.equal(r.resultados.delta.estado,'calculado');a.equal(r.mensajes.filter(m=>m.codigo==='ERR_DELTA_SIN_ALPHA').length,0);});
test('AUD-04 caracteriza overflow de suma B*: calculado y suma de cuotas cero',()=>{const r=calcularBStar([{id:'a'},{id:'b'}],{unidad:'u',valores:[{id:'a',valor:1e308},{id:'b',valor:1e308}]});a.equal(r.estado,'indeterminado');a.equal(r.valor,null);a.match(r.motivo,/finita/);});
test('AUD-05 límite: PF periódico puede converger con arranque equilibrado sin garantía primitiva',()=>{const r=calcularRStar([[0,1],[1,0]]);a.equal(r.estado,'calculado');a.equal(r.diagnostico.periodo,2);a.equal(r.condicionesSuficientes,false);});
test('AUD-06 ausencia, E0, S límites y determinismo repetido',()=>{const q={analisis:modelo(),medicionesSolicitadas:['rStar','delta','s']};a.deepEqual(calcularSolicitud(q),calcularSolicitud(q));a.equal(calcularSolicitud(q).resultados.delta.estado,'indeterminado');const {calcularS}=require('../dist-motor/sustituibilidad'),{calcularContribucionAtribuible:c}=require('../dist-motor/derivados');a.equal(c(.8,0),.8);a.equal(c(.8,1),0);a.equal(calcularS([0,0,0]),0);a.equal(calcularS([1,1,1]),1);});
test('AU-07 corregido: adaptador conserva selección/version externa',()=>{const q=construirSolicitud({nodos:[],relaciones:[],mediciones:[],taxonomiaVersion:'otro@2',dominio:'otro'});a.equal(q.analisis.taxonomiaVersion,'otro@2');});
