'use strict';
const {test}=require('node:test'),a=require('node:assert/strict');
const {calcularSolicitud}=require('../dist-motor/entrada');const {generarHTML}=require('../dist-motor/expediente');
const {mensajesAnalisis}=require('../dist-motor/linter');const q=require('../auditoria/fixtures/diferencial.json');
const unescape=s=>s.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
test('AUD-10 diferencial exacto de valores: solicitud→respuesta→JSON→HTML, sin redondeo oculto',()=>{const r=calcularSolicitud(q),snapshot=JSON.parse(JSON.stringify(r));const h=generarHTML(snapshot);const pres=[...h.matchAll(/<pre class="matriz">([\s\S]*?)<\/pre>/g)].map(m=>{try{return JSON.parse(unescape(m[1]));}catch{return null;}});for(const o of Object.values(snapshot.resultados))a.ok(pres.some(p=>JSON.stringify(p)===JSON.stringify(o.valor)));a.deepEqual(snapshot,JSON.parse(JSON.stringify(r)));const before=JSON.stringify(snapshot);a.equal(h,generarHTML(snapshot,{nodos:[],aristas:[]}));a.equal(JSON.stringify(snapshot),before);});
test('AUD-11 regresión: insumos parciales y configuración conservados en snapshot',()=>{const x=structuredClone(q);x.insumos.danio.tTrayectoria.montoEstimado=null;x.configuracion.sensibilidadExtendida={metodo:'hipercubo_exhaustivo',maxVertices:2};const r=calcularSolicitud(x);a.equal(r.dTotal,null);a.equal(Object.hasOwn(r,'insumos'),true);a.equal(Object.hasOwn(r,'configuracion'),true);a.equal(r.modelo.configuracion,undefined);});
test('AU-03 corregido: duplicado produce mensaje estructural recuperable',()=>{const m=structuredClone(q.analisis);m.relacionesInternas.push({...m.relacionesInternas[0],id:'duplicado'});a.equal(mensajesAnalisis(m,q.medicionesSolicitadas)[0].codigo,'ERR_ESTRUCTURA_INVALIDA');});
test('AUD-13 regresión: cierre inválido produce error local',()=>{const x=structuredClone(q);x.analisis.conexionesCierre[0].rango={min:-9,max:-1};a.equal(calcularSolicitud(x).resultados.rStar.estado,'error');a.match(calcularSolicitud(x).resultados.rStar.motivo,/Rango ausente o inválido/);});
