'use strict';
const {test}=require('node:test'),a=require('node:assert/strict');
const {calcularSolicitud}=require('../dist-motor/entrada');const {generarHTML}=require('../dist-motor/expediente');
const {mensajesAnalisis}=require('../dist-motor/linter');const q=require('../auditoria/fixtures/diferencial.json');
const unescape=s=>s.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
test('AUD-10 diferencial exacto de valores: solicitud→respuesta→JSON→HTML, sin redondeo oculto',()=>{const r=calcularSolicitud(q),snapshot=JSON.parse(JSON.stringify(r));const h=generarHTML(snapshot);const pres=[...h.matchAll(/<pre class="matriz">([\s\S]*?)<\/pre>/g)].map(m=>{try{return JSON.parse(unescape(m[1]));}catch{return null;}});for(const o of Object.values(snapshot.resultados))a.ok(pres.some(p=>JSON.stringify(p)===JSON.stringify(o.valor)));a.deepEqual(snapshot,JSON.parse(JSON.stringify(r)));const before=JSON.stringify(snapshot);a.equal(h,generarHTML(snapshot,{nodos:[],aristas:[]}));a.equal(JSON.stringify(snapshot),before);});
test('AUD-11 caracteriza: insumos externos incompletos/configuración no conservados en respuesta',()=>{const x=structuredClone(q);x.insumos.danio.tTrayectoria.montoEstimado=null;x.configuracion.sensibilidadExtendida={metodo:'hipercubo_exhaustivo',maxVertices:2};const r=calcularSolicitud(x);a.equal(r.dTotal,null);a.equal(Object.hasOwn(r,'insumos'),false);a.equal(Object.hasOwn(r,'configuracion'),false);a.equal(r.modelo.configuracion,undefined);});
test('AUD-12 caracteriza: duplicate válido para formulario provoca excepción no atrapada del linter',()=>{const m=structuredClone(q.analisis);m.relacionesInternas.push({...m.relacionesInternas[0],id:'duplicado'});a.throws(()=>mensajesAnalisis(m,q.medicionesSolicitadas),/Relación duplicada/);});
test('AUD-13 caracteriza: rango inválido de cierre nunca validado como evidencia de D',()=>{const x=structuredClone(q);x.analisis.conexionesCierre[0].rango={min:-9,max:-1};a.equal(calcularSolicitud(x).resultados.rStar.estado,'calculado');});
