const {test}=require('node:test'),a=require('node:assert/strict');const m=require('../dist-motor/ampliacion');const {calcularSolicitud}=require('../dist-motor/entrada');const {generarHTML}=require('../dist-motor/expediente');const f=require('../auditoria/fixtures/diferencial.json');const nodos=[{id:'a'},{id:'b'}];
test('I_inv casos autorales, signos originales, cero e inversión explícita de roles',()=>{for(const [d,e,v]of [[.10,-.56,.17857142857142858],[.6,-.3,2],[.6,-.4,1.5]]){const r=m.indiceInversion({disenadorId:'a',ejecutorId:'b',deltaDisenador:d,deltaEjecutor:e},nodos);a.ok(Math.abs(r.valor-v)<1e-14);a.equal(r.auditoria.deltaEjecutor,e);a.equal(r.auditoria.epsilon,null);const inv=m.indiceInversion({disenadorId:'b',ejecutorId:'a',deltaDisenador:e,deltaEjecutor:d},nodos);a.ok(Math.abs(inv.valor-1/v)<1e-14);a.equal(inv.auditoria.disenadorId,'b');}for(const d of [0,.6]){const r=m.indiceInversion({disenadorId:'a',ejecutorId:'b',deltaDisenador:d,deltaEjecutor:0},nodos);a.equal(r.estado,'indeterminado');a.match(r.motivo,/0|cero/);}a.equal(m.indiceInversion({},nodos).estado,'indeterminado');a.throws(()=>m.indiceInversion({disenadorId:'noexiste',ejecutorId:'b'},nodos),/activos/);a.equal(m.indiceInversion({disenadorId:'a',ejecutorId:'a',deltaDisenador:.6,deltaEjecutor:-.3},nodos).valor,2);});
test('I_inv motor/snapshot/expediente coinciden sin exigir PF ni inferir roles por nombre',()=>{const q=structuredClone(f);q.medicionesSolicitadas=['indiceInversion'];q.insumos.indiceInversion={disenadorId:'a',ejecutorId:'b',deltaDisenador:.1,deltaEjecutor:-.56};const r=calcularSolicitud(q),j=JSON.parse(JSON.stringify(r));a.equal(r.resultados.rStar.estado,'no_solicitado');a.equal(j.resultados.indiceInversion.valor,.1/.56);a.deepEqual(calcularSolicitud(j.snapshot.solicitudOriginal).resultados,j.resultados);a.match(generarHTML(j),/Índice de inversión/);a.match(generarHTML(j),/-0.56/);});
test('AU-13 fraude reservado aunque se suministre función externa o variante histórica',()=>{const {calcularFraudeAnnona}=require('../dist-motor/fraude_annona');a.equal(calcularFraudeAnnona({}, {calcularFraudeAnnona:()=>1}).estado,'indeterminado');const q=structuredClone(f);q.medicionesSolicitadas=['fraudeAnnona'];const r=calcularSolicitud(q);a.equal(r.resultados.fraudeAnnona.reserva,'CON/TAX');a.equal(r.resultados.rStar.estado,'no_solicitado');});
const chevron=require('../auditoria/fixtures/aritmetica-fuente.json').chevron;
test('AU-17 Shapley Chevron canónico corregido y eficiencia, sin selector PF/Shapley',()=>{const ns=[{id:'1'},{id:'2'},{id:'3'}],coaliciones=Object.entries(chevron.coaliciones).map(([ids,valor])=>({miembros:ids.split(''),valor}));if(!coaliciones.some(x=>!x.miembros.length))coaliciones.push({miembros:[],valor:0});const r=m.shapley({unidad:'fracción del daño',coaliciones},ns);a.equal(r.estado,'calculado');r.valor.forEach((x,i)=>a.ok(Math.abs(x.valor-chevron.marginalesExactos[i])<1e-14));a.ok(Math.abs(r.auditoria.sumaAsignada-1)<1e-14);const perm=m.shapley({unidad:'fracción',coaliciones},[ns[2],ns[0],ns[1]]);for(const x of r.valor)a.ok(Math.abs(x.valor-perm.valor.find(y=>y.id===x.id).valor)<1e-14);});
test('Shapley juego incompleto/duplicados/presupuesto y simetría jugador nulo',()=>{const coaliciones=[{miembros:[],valor:0},{miembros:['a'],valor:3},{miembros:['b'],valor:0},{miembros:['a','b'],valor:3}];a.deepEqual(m.shapley({unidad:'MXN',coaliciones},nodos).valor,[{id:'a',valor:3},{id:'b',valor:0}]);a.equal(m.shapley({unidad:'MXN',coaliciones:coaliciones.slice(1)},nodos).estado,'indeterminado');a.throws(()=>m.shapley({unidad:'MXN',coaliciones:[...coaliciones,coaliciones[0]]},nodos),/duplicada/);a.equal(m.shapley({unidad:'MXN',coaliciones},nodos,{maxCoaliciones:2}).estado,'indeterminado');coaliciones[1].valor=coaliciones[2].valor=1;coaliciones[3].valor=4;a.deepEqual(m.shapley({unidad:'MXN',coaliciones},nodos).valor.map(x=>x.valor),[2,2]);});
test('Conversión vital referencia discriminada, cero explícito, sin salario universal',()=>{a.equal(m.conversionVital({monto:800,salarioReferencia:8,unidad:'USD'}).valor,100);a.equal(m.conversionVital({monto:0,salarioReferencia:8,unidad:'USD'}).valor,0);a.equal(m.conversionVital({monto:800,unidad:'USD'}).estado,'indeterminado');a.throws(()=>m.conversionVital({monto:800,salarioReferencia:0,unidad:'USD'}),/positivo/);});
test('J negativo no clamp; V e IAS comparables, ausencia no equivale a cero',()=>{a.equal(m.justicia([-.8,-.8]).valor,-.6000000000000001);a.equal(m.justicia([null,.1]).estado,'indeterminado');const c={referenciaAntes:'G',referenciaDespues:'G2',baseComparabilidad:'mismo evento/universo',valores:[{id:'b',rAntes:.2,rDespues:.6,alphaAntes:0,alphaDespues:.6},{id:'a',rAntes:.8,rDespues:.4,alphaAntes:0,alphaDespues:.4}]};a.ok(Math.abs(m.impacto(c,nodos).valor-.8)<1e-14);a.equal(m.aprendizaje(c,nodos).valor,1);a.equal(m.impacto({...c,baseComparabilidad:null},nodos).estado,'indeterminado');a.throws(()=>m.impacto({...c,valores:[c.valores[0],c.valores[0]]},nodos),/IDs/);});
test('Δ_B absoluta RES-DELTAB sin mezclar beta/alpha, sobre-reversión firmada',()=>{const r=m.brechaBeneficio({unidad:'MXN',valores:[{id:'a',recibido:40000000,revertido:15000000},{id:'b',recibido:10,revertido:20}]},nodos);a.deepEqual(r.valor.map(x=>x.valor),[25000000,-10]);a.equal(r.unidad,'MXN');a.equal(m.brechaBeneficio({unidad:'MXN',valores:[{id:'a',recibido:null,revertido:0},{id:'b',recibido:0,revertido:0}]},nodos).estado,'indeterminado');});
test('Toda ampliación conserva guardas de overflow',()=>{const q=structuredClone(f);q.medicionesSolicitadas=['indiceInversion','conversionVital'];q.insumos.indiceInversion={disenadorId:'a',ejecutorId:'b',deltaDisenador:1e308,deltaEjecutor:1e-308};q.insumos.conversionVital={monto:1e308,salarioReferencia:1e-308,unidad:'USD'};const r=calcularSolicitud(q);a.equal(r.resultados.indiceInversion.estado,'error');a.equal(r.resultados.conversionVital.estado,'error');a.ok(!JSON.stringify(r).includes('"valor":null,"estado":"calculado"'));});

test('ROI neto canónico 825%, costo cero, ausencia y probabilidad nunca inferida',()=>{const input={danioTotal:50e6,costo:1e6,deltaP:.185,unidad:'MXN',baseDeltaP:'escenario externo'};a.equal(m.roiPrevencion(input).valor,8.25);a.equal(m.roiPrevencion({...input,deltaP:null}).estado,'indeterminado');a.throws(()=>m.roiPrevencion({...input,costo:0}),/positivo/);a.equal(m.roiPrevencion({...input,deltaP:0}).valor,-1);});
