'use strict';
const {chromium}=require('playwright');const {spawn}=require('node:child_process');const assert=require('node:assert/strict');
const base=process.env.VERIFY_BASE_URL||'http://127.0.0.1:3100';
const server=process.env.VERIFY_BASE_URL?null:spawn(process.execPath,['node_modules/next/dist/bin/next','start','--port','3100'],{stdio:['ignore','pipe','pipe']});
let browser,page;let logs='';if(server){server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);}
(async()=>{
 try{
  if(server)await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Servidor no arrancó: '+logs)),30000);server.stdout.on('data',()=>{if(logs.includes('Ready')){clearTimeout(timer);resolve();}});server.on('exit',c=>{clearTimeout(timer);reject(Error('Servidor terminó '+c+': '+logs));});});
  const redirect=await fetch(base+'/',{redirect:'manual'});assert.equal(redirect.status,307);assert.equal(redirect.headers.get('location'),'/constructor');
  browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1024,height:900}});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR:',e.stack||e.message);});
  const {GENERICO}=require('../taxonomia/protocolos');
  const fixtureProtocolo={...GENERICO,id:'fixture_ui',version:'2',alcance:'fixture_sin_calibracion',componentesS:[{id:'manual',texto:'Componente alternativo explícito'}],preguntas:[{id:'contexto',texto:'Pregunta alternativa',tipo:'texto'}]};
  await page.route('**/api/protocolos',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({protocolos:[GENERICO,fixtureProtocolo]})}));
  await page.goto(base+'/');await page.getByRole('heading',{name:'¿Qué quieres hacer con este análisis?'}).waitFor();
  await page.getByRole('radio',{name:/Describir y medir/}).check();await page.getByLabel('¿Qué estás analizando? Dominio').fill('Genérico');
  async function tab(name){const b=page.getByRole('navigation',{name:'Pasos del análisis'}).getByRole('button',{name:new RegExp(name)});await b.focus();await page.keyboard.press('Enter');assert.equal(await b.getAttribute('aria-current'),'step');assert.equal(await page.locator('h1').evaluate(el=>el===document.activeElement),true);}
  await tab('Fenómeno y pregunta');await page.getByLabel('Título del análisis').fill('Fixture PF');await page.getByLabel('Pregunta del análisis',{exact:true}).fill('¿Cómo converge?');await page.getByLabel('Describe el fenómeno, evento o estructura que quieres analizar.').fill('Sistema de dos nodos');await page.getByLabel('Evento determinado / punto de cierre (D)').fill('Evento D');
  await tab('Nodos');for(const name of ['A','B']){await page.getByLabel('Nombre del nuevo nodo').fill(name);await page.getByRole('button',{name:'Agregar nodo',exact:true}).click();}
  await tab('Finalidad');await page.getByLabel('Protocolo taxonómico versionado').selectOption('fixture_ui@2');await tab('Discriminaciones');
  assert.equal(await page.getByLabel('Componente alternativo explícito',{exact:true}).count(),2);assert.equal(await page.getByLabel('Pregunta alternativa',{exact:true}).count(),2);
  await tab('Finalidad');await page.getByLabel('Protocolo taxonómico versionado').selectOption('generico@1');
  await tab('Relaciones y soportes');
  for(const [origen,destino,peso] of [['A','A','.9'],['A','B','.4'],['B','A','.1'],['B','B','.6'],['A','D — Evento D','1']]){
   await page.getByLabel('Origen',{exact:true}).selectOption({label:origen});await page.getByLabel('Destino',{exact:true}).selectOption({label:destino});await page.getByLabel('Nivel aplicable discriminado por el analista').selectOption('1');await page.getByLabel('Peso mínimo').fill(peso);await page.getByLabel('Peso máximo').fill(peso);await page.getByRole('button',{name:'Agregar relación',exact:true}).click();
  }
  // AU-03: errores esperados conservan borrador y no rompen render.
  await page.getByLabel('Origen',{exact:true}).selectOption({label:'A'});await page.getByLabel('Destino',{exact:true}).selectOption({label:'A'});await page.getByLabel('Nivel aplicable discriminado por el analista').selectOption('1');await page.getByLabel('Peso mínimo').fill('.9');await page.getByLabel('Peso máximo').fill('.9');await page.getByRole('button',{name:'Agregar relación',exact:true}).click();await page.getByRole('alert').filter({hasText:'Relación duplicada'}).waitFor();assert.equal(await page.getByLabel('Peso mínimo').inputValue(),'.9');assert.equal(await page.getByRole('alert').filter({hasText:'Relación duplicada'}).evaluate(el=>el===document.activeElement),true);await page.getByRole('button',{name:'Agregar relación',exact:true}).click();assert.equal(await page.getByRole('alert').filter({hasText:'Relación duplicada'}).evaluate(el=>el===document.activeElement),true);
  await page.getByLabel('Peso mínimo').fill('-.9');await page.getByRole('button',{name:'Agregar relación',exact:true}).click();await page.getByRole('alert').filter({hasText:'rango no negativo'}).waitFor();
  await page.getByLabel('Origen',{exact:true}).evaluate(el=>el.add(new Option('ID inválido','id_inexistente')));await page.getByLabel('Origen',{exact:true}).selectOption('id_inexistente');await page.getByLabel('Peso mínimo').fill('.9');await page.getByRole('button',{name:'Agregar relación',exact:true}).click();await page.getByRole('alert').filter({hasText:'Identificadores'}).waitFor();await page.getByLabel('Origen',{exact:true}).selectOption({label:'A'});
  await tab('Discriminaciones');
  for(const [name,alpha,s] of [['A','.08',['0','.4','.1']],['B','.03',['.5','.5','.7']]]){
   const card=page.locator('article').filter({has:page.getByRole('heading',{name,exact:true})});
   for(const [i,label] of ['Formalización / procedimiento','Sustituibilidad del actor en la posición','Determinación por sistema / incentivos'].entries())await card.getByLabel(label,{exact:true}).fill(s[i]);
   await card.getByLabel('Estrategia de α (asunción efectiva)').selectOption('discriminado');await card.getByLabel('α entre 0 y 1').fill(alpha);
   await card.locator('summary').filter({hasText:'Índice de integridad causal'}).click();await card.getByLabel('Declaraciones / compromisos (uno por línea)').fill('x\ny');await card.getByLabel('Observaciones (una por línea)').fill('x');await card.getByLabel('Coincidencias identificadas').fill('1');
  }
  await tab('Medidas adicionales');
  await page.locator('summary').filter({hasText:'Índice de inversión — roles explícitos'}).click();await page.getByLabel('Nodo diseñador',{exact:true}).selectOption({label:'A'});await page.getByLabel('Nodo ejecutor',{exact:true}).selectOption({label:'B'});await page.getByLabel('Δ del diseñador (signo original)').fill('.10');await page.getByLabel('Δ del ejecutor (signo original)').fill('-.56');
  await page.locator('summary').filter({hasText:'Juego cooperativo — Shapley exacto'}).click();await page.getByLabel('Unidad del juego cooperativo').fill('MXN');await page.getByRole('button',{name:'Preparar coaliciones del universo activo'}).click();for(const [label,value]of [['v(vacío)','0'],['v(A)','3'],['v(B)','0'],['v(A + B)','3']])await page.getByLabel(label,{exact:true}).fill(value);
await page.getByLabel('Unidad de los beneficios netos').fill('MXN');await page.getByLabel('A: beneficio neto (0 si expresamente no hay beneficio)').fill('30');await page.getByLabel('B: beneficio neto (0 si expresamente no hay beneficio)').fill('10');await page.getByLabel('Unidad común del daño').fill('MXN');for(const [label,v]of [['T_invertido','100'],['T_impedido','20'],['ΔT_trayectoria','30']])await page.getByLabel(label,{exact:true}).fill(v);
  await page.locator('summary').filter({hasText:'Fraude annona — diseño e IIC explícitos'}).click();await page.getByLabel('Diseñador para Fraude annona').selectOption({label:'A'});await page.getByLabel('Variante IIC para Fraude annona').selectOption('congruencia@1');
  await tab('Calcular');for(const label of ['Índice de convergencia de eventos','Índice de sustituibilidad','Contribución atribuible','Condiciones adversas atribuibles','Asimetría repercusiva','Índice de integridad causal','Distribución de beneficio (B*)','Daño total','Ajuste debitor','Robustez de tres escenarios','Índice de inversión','Distribución cooperativa de Shapley','Justicia estructural (J)','Fraude annona'])await page.getByRole('checkbox',{name:label,exact:true}).check();
  const response=page.waitForResponse(r=>r.url().endsWith('/api/calcular'));await page.getByRole('button',{name:'Calcular mediciones seleccionadas'}).click();const data=await (await response).json();if(process.env.EXPECTED_COMMIT)assert.equal(data.snapshot.revisionFuente,process.env.EXPECTED_COMMIT);assert.equal(data.dTotal.dTotal,150);assert.ok(Math.abs(data.rStar[0].valor-.8)<1e-9);assert.equal(data.serieII[0].valor,.5);assert.equal(data.bStar[0].valor,.75);assert.equal(data.declaracion.nivel,'A');assert.equal(data.rStar.length,2);assert.equal(data.resultados.indiceInversion.valor,.1/.56);assert.equal(data.resultados.indiceInversion.auditoria.deltaEjecutor,-.56);assert.equal(data.resultados.shapley.valor[0].valor,3);assert.equal(data.resultados.fraudeAnnona.estado,'calculado');assert.ok(Math.abs(data.resultados.fraudeAnnona.valor-.368)<1e-9);assert.equal(data.resultados.fraudeAnnona.varianteIIC,'congruencia@1');assert.equal(data.snapshot.taxonomiaVersionEfectiva,'generico@1');
  await page.getByText('Declaración A',{exact:true}).waitFor();assert.ok((await page.locator('table').first().innerText()).includes('80.00%'));
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Descargar expediente',exact:true}).click();const file=await download;assert.ok(file.suggestedFilename().endsWith('.html'));const fs=require('node:fs');const html=fs.readFileSync(await file.path(),'utf8');assert.ok(html.includes('150'));assert.ok(html.includes('120'));assert.ok(!html.includes('Tres Series'));assert.ok(html.includes('Índice de inversión'));assert.ok(html.includes('-0.56'));assert.ok(html.includes('Snapshot reproducible'));
  assert.equal(await page.locator('[aria-live=polite]').count()>0,true);
  const contrast=await page.locator('main label,nav button,header a').evaluateAll(els=>{const rgb=s=>s.match(/[\d.]+/g).map(Number),lum=a=>{const c=a.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return .2126*c[0]+.7152*c[1]+.0722*c[2];};return els.filter(el=>el.getClientRects().length).map(el=>{const st=getComputedStyle(el);let p=el,bg;while(p){bg=rgb(getComputedStyle(p).backgroundColor);if(bg.length<4||bg[3]===1)break;p=p.parentElement;}const f=lum(rgb(st.color)),b=lum(bg||[255,255,255]);return {texto:el.innerText,color:st.color,fondo:bg,ratio:(Math.max(f,b)+.05)/(Math.min(f,b)+.05)};});});
  require('node:fs').writeFileSync('/tmp/meriadock-contraste.json',JSON.stringify(contrast,null,2));assert.ok(contrast.length>0);assert.ok(contrast.every(x=>x.ratio>=4.5),JSON.stringify(contrast.filter(x=>x.ratio<4.5)));
  assert.equal((await page.request.get(base+'/api/hello')).status(),404);
  const fixture=require('../auditoria/fixtures/diferencial.json');
  async function post(q){const res=await page.request.post(base+'/api/calcular',{data:q});return {status:res.status(),data:await res.json()};}
  const evidencias=[];
  for(const nivel of [-1,9,1.5]){const q=structuredClone(fixture);q.analisis.conexionesCierre[0].evidenciaNivel=nivel;const r=await post(q);assert.equal(r.data.resultados.rStar.estado,'error');evidencias.push({caso:'nivel cierre '+nivel,estado:r.data.resultados.rStar.estado});}
  for(const rango of [{min:-1,max:1},{min:1,max:0}]){const q=structuredClone(fixture);q.analisis.conexionesCierre[0].rango=rango;const r=await post(q);assert.equal(r.data.resultados.rStar.estado,'error');}
  const q0=structuredClone(fixture);q0.analisis.conexionesCierre[0].evidenciaNivel=0;const r0=await post(q0);assert.equal(r0.data.resultados.rStar.estado,'indeterminado');assert.ok(!r0.data.modelo.nodosActivos.some(n=>n.id==='D'));evidencias.push({caso:'cierre E0',estado:r0.data.resultados.rStar.estado});
  const overflow=structuredClone(fixture);overflow.insumos.beneficios.valores.forEach(x=>x.valor=1e308);overflow.insumos.danio.tInvertido.monto=1e308;overflow.insumos.danio.tImpedido.monto=1e308;const ro=await post(overflow);assert.equal(ro.data.resultados.bStar.estado,'indeterminado');assert.equal(ro.data.resultados.dTotal.estado,'error');evidencias.push({caso:'overflow B*/daño',estadoB:ro.data.resultados.bStar.estado,estadoD:ro.data.resultados.dTotal.estado});
  const parcial=structuredClone(fixture);parcial.medicionesSolicitadas=['rStar','dTotal','desconocido'];parcial.analisis.relacionesInternas.push({...parcial.analisis.relacionesInternas[0],id:'duplicada'});const rp=await post(parcial);assert.equal(rp.data.resultados.rStar.estado,'error');assert.equal(rp.data.resultados.dTotal.estado,'calculado');assert.equal(rp.data.resultados.desconocido.estado,'error');evidencias.push({caso:'fallos locales e independencia',validacion:rp.data.validacion});
  const faltaVersion=structuredClone(fixture);faltaVersion.analisis.taxonomiaVersion='inexistente@999';assert.equal((await post(faltaVersion)).status,400);
  const inv=structuredClone(fixture);inv.medicionesSolicitadas=['indiceInversion'];inv.insumos.indiceInversion={disenadorId:'a',ejecutorId:'b',deltaDisenador:.6,deltaEjecutor:0};const ri=await post(inv);assert.equal(ri.data.resultados.indiceInversion.estado,'indeterminado');assert.equal(ri.data.resultados.rStar.estado,'no_solicitado');evidencias.push({caso:'I_inv denominador cero',resultado:ri.data.resultados.indiceInversion});
  // Reaceptación P1/P2 restante sobre el mismo servidor/revisión.
  const reconstruido=await post(data.snapshot.solicitudOriginal);assert.deepEqual(reconstruido.data.resultados,data.resultados);assert.deepEqual(reconstruido.data.escenarios,data.escenarios);evidencias.push({caso:'snapshot reconstruye resultados/escenarios exactos',estado:'conforme'});
  const externo=structuredClone(fixture);externo.analisis.nodosActivos.forEach(n=>delete n.alpha);externo.medicionesSolicitadas=['delta'];const re=await post(externo);assert.equal(re.data.resultados.delta.estado,'calculado');assert.ok(!re.data.mensajes.some(x=>x.codigo==='ERR_DELTA_SIN_ALPHA'));evidencias.push({caso:'linter usa alpha externo efectivo',estado:re.data.resultados.delta.estado});
  const periodic=structuredClone(fixture);periodic.medicionesSolicitadas=['rStar'];periodic.analisis.relacionesInternas=[{id:'ab',origen:'a',destino:'b',evidenciaNivel:1,rango:{min:2,max:2}},{id:'ba',origen:'b',destino:'a',evidenciaNivel:1,rango:{min:1,max:1}}];periodic.configuracion={pf:{maxIteraciones:50}};const rc=await post(periodic);assert.equal(rc.data.resultados.rStar.estado,'indeterminado');assert.equal(rc.data.escenarios.central.eigenvalorDominante,null);assert.equal(rc.data.escenarios.central.estimacionRho,1.5);evidencias.push({caso:'rho estimado no validado',rho:rc.data.escenarios.central.estimacionRho,residuo:rc.data.escenarios.central.residuo});
  const hip=structuredClone(periodic);hip.medicionesSolicitadas=['sensibilidadExtendida'];hip.analisis.relacionesInternas.forEach(e=>e.rango={min:0,max:1});hip.configuracion.sensibilidadExtendida={metodo:'hipercubo_exhaustivo',maxVertices:4};const rh=await post(hip);assert.equal(rh.data.resultados.sensibilidadExtendida.estado,'indeterminado');assert.equal(rh.data.resultados.sensibilidadExtendida.fallidas,3);assert.equal(rh.data.resultados.sensibilidadExtendida.completitud,'parcial');evidencias.push({caso:'sensibilidad parcial',total:rh.data.resultados.sensibilidadExtendida.totalMuestras,fallidas:rh.data.resultados.sensibilidadExtendida.fallidas});
  const identidades=['a','b','c'],permutaciones=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]];
  for(const perm of permutaciones){const q=structuredClone(fixture);q.medicionesSolicitadas=['robustez'];q.analisis.nodosActivos=perm.map(i=>({id:identidades[i],nombre:identidades[i]}));q.analisis.relacionesInternas=identidades.flatMap((id,i)=>identidades.map(destino=>({id:id+'_'+destino,origen:id,destino,evidenciaNivel:1,rango:{min:i===0?3:1,max:i===0?3:1}})));const rr=await post(q);assert.equal(rr.data.resultados.robustez.estado,'indeterminado');assert.equal(rr.data.resultados.robustez.valor,null);}
  evidencias.push({caso:'empate secundario invariante en seis permutaciones',estado:'indeterminado'});
  const estados=structuredClone(fixture);estados.medicionesSolicitadas=['bStar','dTotal','rStar','desconocido'];estados.insumos.beneficios.valores.forEach(x=>x.valor=0);estados.insumos.danio.tTrayectoria.montoEstimado=null;const rs=await post(estados);assert.equal(rs.data.resultados.bStar.estado,'no_aplicable');assert.equal(rs.data.resultados.dTotal.estado,'indeterminado');assert.equal(rs.data.resultados.rStar.estado,'calculado');assert.equal(rs.data.resultados.desconocido.estado,'error');assert.equal(rs.data.resultados.iic.estado,'no_solicitado');evidencias.push({caso:'cinco estados explícitos',estado:'conforme'});
  for(const [alpha,coincidencias,esperado] of [[.1,1,.432],[.6,1,.192],[.1,4,.108]]){const q=structuredClone(fixture);q.medicionesSolicitadas=['fraudeAnnona'];q.analisis.relacionesInternas.forEach(e=>e.rango={min:e.origen==='a'?.6:.4,max:e.origen==='a'?.6:.4});q.insumos.insumosAlpha=[{id:'a',estrategia:'discriminado',valor:alpha}];q.insumos.nodosIIC=[{id:'a',declarado:['1','2','3','4','5'],observado:['1','2','3','4','5'],coincidencias,varianteIIC:'congruencia@1'}];q.insumos.fraudeAnnona={disenadorId:'a',rol:'disenador',varianteIIC:'congruencia@1'};const r=await post(q);assert.equal(r.data.resultados.fraudeAnnona.estado,'calculado');assert.ok(Math.abs(r.data.resultados.fraudeAnnona.valor-esperado)<1e-9);evidencias.push({caso:'Fraude producto canónico '+esperado,resultado:r.data.resultados.fraudeAnnona});delete q.insumos.fraudeAnnona.varianteIIC;assert.equal((await post(q)).data.resultados.fraudeAnnona.estado,'indeterminado');}
  const fsE=require('node:fs');fsE.writeFileSync('/tmp/meriadock-evidencia-'+(process.env.VERIFY_BASE_URL?'produccion':'local')+'.json',JSON.stringify({base,revision:data.snapshot.revisionFuente,pruebas:evidencias,resultadoUI:data,contraste:contrast},null,2));
  const catalogoReal=await (await page.request.get(base+'/api/protocolos')).json();assert.ok(catalogoReal.protocolos.some(p=>p.id==='tax-cap01'&&p.universales.length===4));
  const taxPage=await browser.newPage();await taxPage.goto(base+'/constructor');await taxPage.getByLabel('Protocolo taxonómico versionado').selectOption('tax-cap01@1');assert.equal(await taxPage.getByLabel('¿Qué estás analizando? Dominio').inputValue(),'penal_civil');await taxPage.getByRole('navigation').getByRole('button',{name:/Nodos/}).click();await taxPage.getByLabel('Nombre del nuevo nodo').fill('Diseñador sectorial');await taxPage.getByRole('button',{name:'Agregar nodo',exact:true}).click();await taxPage.getByRole('navigation').getByRole('button',{name:/Discriminaciones/}).click();await taxPage.getByLabel('¿Existía deber documentado y conocimiento de la situación para la omisión?').waitFor();await taxPage.locator('summary').filter({hasText:'Orientación taxonómica — Hijos, rutas A/B y límites'}).click();await taxPage.getByLabel('Diseñador sectorial: ¿Existe señal de energía ante el evento?').selectOption('no');await taxPage.getByLabel('Diseñador sectorial: ¿La ausencia es selectiva o generalizada?').selectOption('generalizada');await taxPage.getByLabel('Diseñador sectorial: ¿Falta búsqueda causal ante eventos que la requerían?').selectOption('no');await taxPage.getByRole('status').filter({hasText:'Orientación: REQUIERE_ECO'}).waitFor();assert.equal(await taxPage.getByLabel('S efectivo discriminado (confirmación obligatoria)').inputValue(),'');await taxPage.getByLabel('S efectivo discriminado (confirmación obligatoria)').fill('.4');await taxPage.getByLabel('Confirmo el S efectivo de Diseñador sectorial tras revisar las orientaciones').check();await taxPage.getByLabel('Justificación de S efectivo — Diseñador sectorial').fill('Discriminación explícita de protocolo');assert.equal(await taxPage.getByLabel('Confirmo el S efectivo de Diseñador sectorial tras revisar las orientaciones').isChecked(),true);await taxPage.close();
  await page.screenshot({path:process.env.VERIFY_BASE_URL?'/tmp/meriadock-produccion.png':'/tmp/meriadock-verificacion.png',fullPage:true});assert.deepEqual(errors,[]);console.log('UI → API → PF/IIC/B*/D_total/AD → resultados → descarga: VERDE; sin errores de página.');
 }catch(e){if(page){console.error('Estado de interfaz:',await page.locator('body').innerText());await page.screenshot({path:'/tmp/meriadock-error.png',fullPage:true}).catch(()=>{});}throw e;}finally{if(browser)await browser.close();if(server)server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
